### PR TITLE
Updated copyright year

### PR DESCRIPTION
**Pull request by comradekingu**
Would have fixed on Weblate if direct editing of source strings was turned on.
An "ignore-same" flag for https://hosted.weblate.org/translate/gdm-settings/language-names/en/?checksum=0837b26cdffae9b8 would also do nicely.

### CODE REVIEW

**Comment by realmazharhussain** [comment]
This had already been done in commit f245d3000200fa6be2a35c7f6ac45b131dadb5d6.

https://github.com/realmazharhussain/gdm-settings/blob/f245d3000200fa6be2a35c7f6ac45b131dadb5d6/src/about.py#L30

**Comment by realmazharhussain** [comment]
> An "ignore-same" flag for https://hosted.weblate.org/translate/gdm-settings/language-names/en/?checksum=0837b26cdffae9b8 would also do nicely.

This string has proper translation for a lot of languages. That flag will be counted as a regression for those languages.

You can skip the check for your language very easily.

**Comment by comradekingu** [comment]
OK.
The flag isn't "read-only". "ignore-same" only prevents triggering the unchanged check, for when "copyright" is the word "copyright", leaving the string unaltered.

**Comment by realmazharhussain** [comment]
> The flag isn't "read-only". "ignore-same" only prevents triggering the unchanged check, for when "copyright" is the word "copyright", leaving the string unaltered.

I don't understand what you mean. Can you, please, rephrase it.

**Comment by comradekingu** [comment]
"ignore-same" only removes the (dismissable) check that is triggered when the source and translation are found to match 100%.

**Comment by realmazharhussain** [comment]
Checks are there for a reason. Translators of other languages won't expect "Unchanged Translation" check to be disabled by default for this string.

**Comment by comradekingu** [comment]
As an outmost-quality assurance, that makes sense. I'd take the trade though. ignore-flags suit that purpose.
Not a big issue one way or the other.

**Pull request closed without merging**
