### PR TITLE
feat: use AdwABoutDialog (#89)

### PR DESCRIPTION
**Pull request by 0xMRTT**

### CODE REVIEW

**Comment by 0xMRTT** [comment]
image

**Comment by realmazharhussain** [comment]
Thank you very much for contributing. But I do not plan on switching to AdwAboutDialog untill LibAdwaita 1.2 is out.

Also, there are a few issues with your PR.

- It is not signed (I can ignore this one).
- It does a lot of style changes to the code which are not related to AdwAboutWindow.
- You sneakily put your name in the developers' list which is another unrelated change.

**Comment by 0xMRTT** [comment]
So, should I close this PR and wait?

**Comment by realmazharhussain** [comment]
> So, should I close this PR and wait?

Yes.

**Comment by realmazharhussain** [comment]
Also, you might want to sign your commits. Otherwise anyone can impersonate you and wreak heavoc on your account.

Another thing; You should ask in the issue (or create one if it doesn't exist) before actually starting to write code for a PR so that you don't waste your time. And when you do write code, make only the changes previously discussed in the issue.

This way, your PRs will have a much more chance of getting merged.

If you need help on signing commits, you could ask on r/git subreddit or #git matrix channel or hit me up at <realmazharhussain@gmail.com>

**Comment by 0xMRTT** [comment]
I know how to sign commits, it's just because my setup is new and I don't setup git gpg again.

**Comment by realmazharhussain** [comment]
Understandable

**Pull request closed without merging**
